Added trim to address #3
serilog/serilog-sinks-debug pull request #4
Opened 2018-01-05 00:57 UTC by HakanL

2018-01-05 02:10 UTC, nblumhardt requested changes
Thanks for the PR, Hakan! Agree strongly that we should fix this.

I think the root cause is actually my use of `Debug.WriteLine()` - it should be `Debug.Write()`.

2018-01-05 02:10 UTC, nblumhardt commented on src/Serilog.Sinks.Debug/Sinks/Debug/DebugSink.cs
> +                System.Diagnostics.Debug.WriteLine(buffer.ToString().Trim());
Instead of trimming off the newline, we should use `Debug.Write()` - the use of `WriteLine()` here is a mistake.

2018-01-05 02:34 UTC, HakanL commented
But wouldn’t that cause a template without NewLine to all be on one line? I compare with the Trace sink. 

Sent from my iPhone

> On Jan 4, 2018, at 6:10 PM, Nicholas Blumhardt <notifications@github.com> wrote:
> 
> @nblumhardt requested changes on this pull request.
> 
> Thanks for the PR, Hakan! Agree strongly that we should fix this.
> 
> I think the root cause is actually my use of Debug.WriteLine() - it should be Debug.Write().
> 
> In src/Serilog.Sinks.Debug/Sinks/Debug/DebugSink.cs:
> 
> > @@ -34,7 +34,7 @@ public void Emit(LogEvent logEvent)
>              using (var buffer = new StringWriter())
>              {
>                  _formatter.Format(logEvent, buffer);
> -                System.Diagnostics.Debug.WriteLine(buffer.ToString());
> +                System.Diagnostics.Debug.WriteLine(buffer.ToString().Trim());
> Instead of trimming off the newline, we should use Debug.Write() - the use of WriteLine() here is a mistake.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2018-01-05 02:38 UTC, nblumhardt commented
Yes, that's the case - but a template without newlines is valid for Serilog (there's no requirement that output is newline-delimited). The standard console, file, text writer sinks etc. all follow this pattern.

E.g. https://github.com/serilog/serilog-sinks-console/blob/dev/src/Serilog.Sinks.Console/Sinks/SystemConsole/ConsoleSink.cs#L63

The trace sink is an exception because there's no `Write()` equivalent in the trace API.

2018-01-05 03:08 UTC, HakanL commented
Ah got it, makes sense then to use Write() :)

Sent from my iPhone

> On Jan 4, 2018, at 6:10 PM, Nicholas Blumhardt <notifications@github.com> wrote:
> 
> @nblumhardt requested changes on this pull request.
> 
> Thanks for the PR, Hakan! Agree strongly that we should fix this.
> 
> I think the root cause is actually my use of Debug.WriteLine() - it should be Debug.Write().
> 
> In src/Serilog.Sinks.Debug/Sinks/Debug/DebugSink.cs:
> 
> > @@ -34,7 +34,7 @@ public void Emit(LogEvent logEvent)
>              using (var buffer = new StringWriter())
>              {
>                  _formatter.Format(logEvent, buffer);
> -                System.Diagnostics.Debug.WriteLine(buffer.ToString());
> +                System.Diagnostics.Debug.WriteLine(buffer.ToString().Trim());
> Instead of trimming off the newline, we should use Debug.Write() - the use of WriteLine() here is a mistake.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2018-01-10 00:12 UTC, HakanL reviewed
Sorry about the delay, didn't realize you wanted me to update the PR :)

2018-01-10 00:44 UTC, HakanL commented
So much for coding this change in the Github editor... So with .NET Standard/Core and the System.Diagnostics.Debug NuGet package, it turns out Debug.Write is no longer available, only WriteLine. So I think we need to stick to the Trim() version?

2018-01-10 01:52 UTC, nblumhardt commented
Thanks for the follow-up. It looks like `Write()` was added back in .NET Standard 2.0 - I think it's worth re-targeting the package if we can. Perhaps `#if DEBUG_WRITE /* new code */ #else /* old version */ #endif`?

2018-01-10 02:24 UTC, HakanL commented
I can upgrade to .NET Standard 2.0, but I don't think that's possible via #ifdef?

2018-01-11 00:21 UTC, nblumhardt commented
There are a couple of steps, but it works quite nicely.

First, multiple `<TargetFrameworks>` are specified:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Serilog.csproj#L7

Then, `<DefineConstants>` is used in a conditional `<PropertyGroup>`:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Serilog.csproj#L64

Finally, the constants are available in the code:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Context/LogContext.cs#L24

Cheers!

2018-01-11 02:13 UTC, HakanL commented
ok, this PR got messier than I had anticipated :) But see if it looks better now?

2018-01-11 05:55 UTC, nblumhardt commented
Looks great, thanks @HakanL !

2018-01-11 05:55 UTC, merged